### PR TITLE
Merge from evanx/redexutil

### PR DESCRIPTION
**Pull request by ion-willo**

### CODE REVIEW

**Comment by ion-willo** [comment]
@evanx I should probably forked this repo instead. If you give me write access to this repo, I'll not bother you so much :smile:

**Comment by evanx** [comment]
@ion-willo - have made you collaborator which should give write access :)

**Comment by ion-willo** [comment]
@evanx  Just tried to push to it and, 
`! [remote rejected] master -> master (permission denied)`
Not sure if there are any rules set up on this repo?

**Comment by evanx** [comment]
@ion-willo - ionteam had write perms but have added your username now as well

**Comment by evanx** [comment]
@ion-willo - ah this team needs to be updated - still has Ivo who left WWC -  but not yourself - see https://github.com/orgs/ionteamza/teams/ionteam

**Comment by ion-willo** [comment]
@evanx Awesome thanks! That worked.

**Pull request merged**
